# Generated by Django 5.1.1 on 2024-09-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiceRecognition', '0002_sentences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentences',
            name='sentence',
            field=models.TextField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='text',
            field=models.TextField(db_index=True, max_length=500),
        ),
    ]
